version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres-simple-hotwire
      - redis-simple-hotwire
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://root:@postgres-simple-hotwire:5432/simple-hotwire
      DATABASE_NAME: simple-hotwire
    networks:
      internal:
  "postgres-simple-hotwire":
    image: postgres:latest
    ports:
      - "6832:5432"
    volumes:
      - .:/app:cached
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: simple-hotwire
      POSTGRES_USER: root
    networks:
      internal:
  "redis-simple-hotwire":
    image: redis:latest
    expose:
      - "6379"
    networks:
      internal:
volumes:
  postgres_data:
networks:
  internal: