version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://root@postgres:5432/simple-hotwire
  postgres:
    image: postgres:latest
    expose:
      - "5432:5432"
    volumes:
      - .:/app:cached
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: simple-hotwire
      POSTGRES_USER: root
  redis:
    image: redis:latest
volumes:
  postgres_data: