shared: &shared
  adapter: postgres
  encoding: utf-8
  pool: 5

development:
  <<: *shared
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *shared
  database: simple-hotwire_test

production:
  <<: *shared
  url: <%= ENV['DATABASE_URL'] %>
