shared: &shared
  adapter: postgresql
  encoding: utf-8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *shared
  host: postgres
  port: 6832
  database: simple-hotwire_development

test:
  <<: *shared
  database: simple-hotwire_test

production:
  <<: *shared
